      
	  PROGRAM FLUJOS
	  !USA LA BIBLIOTECA NUMERICA MS (MICROSOFT) IMSL 	  
	  USE MSIMSL
	  !USE mDATA01

! FLUJOS Programa para la obtencion de la matriz Ybus por inspeccion de 
! J.J. TREJO (08-JUNIO-2024)

	  CALL LEEDATOS
	  CALL PORTADA
	  CALL INSPECCION
	  CALL AUXILIAR
	  !CALL RVOLTAJES

	  PAUSE '>>ESTOY ESPERANDO QUE TECLEES ENTER'

	  WRITE(*,*)'YA TERMINE EL PROGRAMA'

	  END PROGRAM FLUJOS