MODULE mDATA

!Sbase: POTENCIA BASE EN MVA
!Faa: FACTOR DE ACELERACION PARA CORRECCION DE VOLTAJES
!tol: TOLERANCIA MAXIMA PERMITIDA
!n: NUMERO DE NODOS
!e: NUMERO DE ELEMENTOS
!Slack: NODO SLACK
!imax: NUMERO MAXIMO DE ITERACIONES
!p: BUS DE SALIDA DE TODOS LOE ELEMENTOS
!q: BUS DE LLEGADA DE TODOS LOS ELEMENTOS
!TipoE: TIPO DE NODO: (1) SLACK (2) CARGA (3) VOLTAJE CONTROLADO
!zpq: IMPEDANCIA SERIE 
!yppqs2: ADMITANCIA PARALELO DE LA LINEA
!EN:
!Ep: VOLTAJE EN EL NODO 
!SGen: POTENCIA DE GENERACION
!Scarga: POTENCIA DE CARGA
!Ybus: MATRIZ YBUS DEL SISTEMA
!Sneta:
!KL: PARAMETROS KLp
!YL: PARAMETROS YLpq
!EpTemp: GUARDA EL VALOR DE Ep 
!DeltaEp: CAMBIO EN EL VOLTAJE Ep nuevo - Ep anterior
!Epacel: VOLTAJE ACELERADO
!Fpot: FLUJOS DE POTENCIA

REAL :: Sbase, Faa, tol
INTEGER :: n, e, Slack, imax
INTEGER, ALLOCATABLE :: p(:), q(:), TipoE(:)
COMPLEX, ALLOCATABLE :: zpq(:), yppqs2(:) 
COMPLEX, ALLOCATABLE :: EN(:), Ep(:), SGen (:), Scarga(:)
COMPLEX, ALLOCATABLE :: Ybus(:,:)
COMPLEX, ALLOCATABLE :: Sneta(:), KL(:), YL(:,:)
COMPLEX :: EpTemp, DeltaEp
COMPLEX, ALLOCATABLE :: Epacel(:), Fpot(:,:)

END MODULE mDATA